export const httpMessage = {
     VALIDATION_ERROR : "INPUT FIELD MUST ENTER A VALUE",
     NOT_CREATED : "CONTACT NOT SAVED",
     CREATED : "CONTACT CREATED || SAVED",
     USEREXIST : 'THE EMAIL IS ALREADY EXIST',
     RESPONSE : 'RESPONSE NOT WORKING IN CONTROLLERS',
    INTERNAL_SERVER_ERROR : "INTERNAL SERVER ERROR",

     
}


export const httpStatus = {
    CONFLICT : 409 ,
    INTERNAL_SERVER_ERROR : 500,
    CREATED : 200,
    BADREQUEST : 400
}